### ISSUE TITLE
Clarify v2 endpoint

### ISSUE THREAD

**Issue by mario** [nextcloud/activity#104]
Can you please clarify the differences between v1 and v2 endpoints (docs for v1 doesn't seem to exist), and in which version did this change?

**Comment by nickvergessen** [comment]
The v2 endpoint is not yet public API. I hope we can do that for 12.

**Comment by mario** [comment]
@nickvergessen thanks for clarifying that. Do you have the documentation for v1, and which oc/nc version is needed to use it? Also is it possible to check via capabilities which version of endpoint is there?

**Comment by nickvergessen** [comment]
v1 is available since ownCloud 6 IIRC. v2 will come with an entry in capabilities once it's ready for use.
Docs for v1 are not available, but it's also quite simple: `ocs/v1.php/cloud/activity`
It always returns the 30 last entries, pagination is not available. HTTP status code is always 200 or 503 (instance is in maintenance mode).

Available keys per element in the result:
https://github.com/nextcloud/activity/blob/master/lib/Controller/APIv1.php#L96-L101

May I ask, what exactly you are looking for? Do you want to implement it in an app or something?

**Comment by mario** [comment]
@nickvergessen thanks - this is useful. Indeed, I'm looking to integrate activity into the app :)

**Comment by nickvergessen** [comment]
Which app? Nextcloud Android App?

**Comment by mario** [comment]
@nickvergessen yup yup.

**Comment by nickvergessen** [comment]
Okay in that case I would say develop against the private v2 endpoint
I will take care that it will be in the final release for 12, and you just need to replace the URL in the end.

**Comment by mario** [comment]
Okay, so you're suggesting support only v12 and up? Understood, and thanks! Let me know when you know a bit more about capabilities entry as well.

**Comment by nickvergessen** [comment]
If you want to code something, you might also have a look at the notifications API. I think that's even more important to bring to the client and is already done server-wise: https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md

But might not be as fast forward how they should be handled on the device (also with account switching etc.)

**Comment by mario** [comment]
@nickvergessen already looking at that as well. Tons of things to do, so little time ... ah :) Need to get up to speed with the Android codebase first and all the relevant APIs.
