### ISSUE TITLE
Activities coulld not be loaded

### ISSUE THREAD

**Issue by Its-egner** [nextcloud/activity#1196]
### Steps to reproduce
1. klick 3 Dots next to file
2. Klick Details
3. Error Messages: Activities coulld not be loaded

### Expected behaviour
Activitys are shown

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Centos
**Web server:**
Docker
**Database:**
Mariadb Docker
Docker

**Nextcloud version:** (see Nextcloud admin page)
26.0.2
**Where did you install Nextcloud from:**
Github
**Signing status:**

```
It was said, this Bug gets Fixed in 26.0.2
```

**Comment by Fenn-CS** [comment]
Could this be related to activities not loading at all on the activities app landing screen?
![activities-not-loading](https://github.com/nextcloud/activity/assets/14317775/f1c76561-d719-43a4-96e5-bfeace6fe0f8)

While reporting this on terminal

```js
Uncaught TypeError: i.Activity.Templates is undefined
    NextJS 3
    Ge Underscore
    NextJS 5
    jQuery 8
    NextJS 4
    jQuery 10
    <anonymous> NextJS
    jQuery 12
    Webpack 7

````

**Comment by Fenn-CS** [comment]
cc : @nextcloud/server-backend can someone confirm they have this too?

**Comment by skjnldsv** [comment]
I can reproduce the issue.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'userLocal')
    at Object.parseParameter (richObjectStringParser.js:1:1076)
    at richObjectStringParser.js:1:278
    at Function.each (each.js:14:1)
    at Object.parseMessage (richObjectStringParser.js:1:192)
    at Object.addActivity (script.js:1:4262)
    at Object.appendActivityToContainer (script.js:1:3435)
    at Object.handleActivitiesCallback (script.js:1:2755)
    at Object.success (script.js:1:2330)
    at fire (jquery.js:3536:1)
    at Object.fireWith [as resolveWith] (jquery.js:3666:1)
```

**Comment by benklaasen** [comment]
Since upgrading from Nextcloud 27.n.5 to 28.0.1, I'm experiencing the same issue as described by @Fenn-CS, but the cause may be different; in the JS console, I get the error:

```
Loading module from “https://my.nextcloud.dom/apps/activity/js/activity-app.mjs?v=786fb033-11” was blocked because of a disallowed MIME type (“text/html”).
```
![Screenshot from 2023-12-27 00-17-16](https://github.com/nextcloud/activity/assets/651495/e73fc35b-8e5d-4053-ad2f-db4ad8ff6210)

Since applying this upgrade, the Log Viewer app also fails to load logs, because of the same error; see https://github.com/nextcloud/logreader/issues/815

I'm running nginx 1.25.1 and PHP 8.1.2. 

(This is a long-established, robust personal Nextcloud instance which I've upgraded all the way from Nextcloud 13 to 28, and which until now has been running flawlessly.)

**Comment by skjnldsv** [comment]
@benklaasen my guess, your nginx config is outdated and you're not serving mjs files properly
Check the docs: https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

**Comment by joshtrichards** [comment]
Not a problem today.
