### ISSUE TITLE
Disable activity filters based on enabled apps

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#150]
* disable "Two-factor authentication" if none of those apps is enabled (cc @ChristophWurst)
* disable "Calendars" and "Todos" if the Calendar app is disabled

cc @nickvergessen 

@oparoz

**Comment by MorrisJobke** [comment]
@jancborchardt for your opinion ;)

**Comment by ChristophWurst** [comment]
> disable "Calendars" and "Todos" if the Calendar app is disabled

Note that calendars can be used even without the calendar app.

**Comment by ChristophWurst** [comment]
> MorrisJobke added the 3. to review label 10 minutes ago

Are you sure about that? :-P

**Comment by MorrisJobke** [comment]
> Note that calendars can be used even without the calendar app.

Yes I know, but on an instance where there is no calendar available not advertised this looks super strange.



> Are you sure about that? :-P

Habit from opening PRs :P

**Comment by nickvergessen** [comment]
The dav filters are intentionally done by dav app and not the UI apps, this requested from calendar+contacts. They are not the api that is interacted with, people that only manage with their phones still might want to see the activity.

For two factor I agree, but that has to be fixed in the two factor app, or hacked into the activity manager, both are in the server repo, therefor I'm closing this...

**Comment by jancborchardt** [comment]
> disable "Calendars" and "Todos" if the Calendar app is disabled

Maybe a better middle path is to disable that / not show that when the calendar app is disabled _and_ there are no entries in there. Cause if Calendars are used via dav, it should show there. :)

**Comment by nickvergessen** [comment]
Default calendar is created on first login, so there is always an entry... also that gets too messy from my pov

**Comment by jancborchardt** [comment]
Of course I meant real entries reflecting actual use. If neither Calendar nor Tasks are used, those sidebar entries only serve to confuse users.

**Comment by nickvergessen** [comment]
So for each activity app page load you want to query the dav backends if the user has more then 1/2 calendar (personal + birthdays) and or has entries in these calendars, ignoring artificial entries (birthdays).
Sorry but this is way too much hacking for such a minor thing. There is a possible monkey patch (remove filter from dav's info.xml) which is sufficient enough...

**Comment by helmut72** [comment]
Thanks a lot. Removing the part in dav's info.xml works. Because this **really** confuse normal users!

We use another Groupware and users ask about Calendar and Tasks in Nextcloud, which is disabled.

If they click on Activity's Calendar and Task, it additionally won't stop loading, which is a bad behavior=bug ... loading endless hyper-confuse our users :)
