### ISSUE TITLE
NC12 ignores custom mail templates for the activity app

### ISSUE THREAD

**Issue by BenS89** [nextcloud/activity#160]
**Steps to reproduce:**

 - Create a custom mail template for the activity app under /themes/customTheme/apps/activity/templates/email.notification.php
- configure your custom theme in the nextcloud config
- Do something and wait for the activity app so send notification mails

**Expected behavior:**
The notification mail uses the configured template (as it was in NC11)

**Actual behaviour:**
The configured template gets ignored. The mail includes the default template text.

Enabled apps:
Calendar 	1.5.3
Contacts 1.5.3

PHP-Version: 7.1.1
OS: Embedded QNAP-Linux

**Comment by nickvergessen** [comment]
Yeah the app was migrated to the new email templating system. Not sure if that allows theming yet.

What would youblike to change? Wording or styling?

**Comment by BenS89** [comment]
Wording. I temporarily fixed it with changing the corresponding strings within the.js / .json files

**Comment by nickvergessen** [comment]
You should be able to replace language files or parts of them with theming as well

**Comment by phatair** [comment]
Hi,
i would like to change the logo "custom cloud" in the mail notification. How can i do this?
Thanks for your help.

**Comment by nickvergessen** [comment]
That's a server side issue, see https://github.com/nextcloud/server/issues/5036

**Comment by elpraga** [comment]
Which files should I edit when I want to modify the default email being sent @nickvergessen ? The default template uses `.svg` images, which would be fine, if google wasn't blocking all svg in gmail. I would like to change them to `.png` equivalents, so that users can actually see them.

**Comment by nickvergessen** [comment]
That issue is being worked on in https://github.com/nextcloud/server/issues/5075

**Comment by elpraga** [comment]
Thanks!

**Comment by ams-tschoening** [comment]
> Yeah the app was migrated to the new email templating system. Not sure if that allows theming yet.

Where can I found more info about that new templating system and how it interacts with other apps? Are the only available infos [these in the docs](https://docs.nextcloud.com/server/21/admin_manual/configuration_server/email_configuration.html#using-email-templates)? Those don't explain much about integration with other apps, how different templates are distinguished from each other etc. I need to know how e.g. the activity app generates mails and how I can customize those entirely. I can't even find code in the app implementing `IEMailTemplate`, only very few mentions of similar names like the [following](https://github.com/nextcloud/activity/blob/e10f9e1a09389748e93906bd67ef7d33dad28edb/lib/DigestSender.php#L175):

```php
$template = $this->mailer->createEMailTemplate('activity.Notification', [
```

But those calls don't explain where templates/classes/... need to be stored to customize things.

**Comment by ams-tschoening** [comment]
I've found how individual templates are distinguished: `activity.Notification` from the example above is the requested template and while it's not documented pretty well, that name is forwarded as `$emailId` to implementations of [IEMailTemplate](https://github.com/nextcloud/server/blob/b0fe408d1f08958d1d00c98810675cc8a70df686/lib/private/Mail/EMailTemplate.php#L355):

```php
public function __construct(Defaults $themingDefaults,
				IURLGenerator $urlGenerator,
				IFactory $l10nFactory,
				$emailId,
				array $data) {
	$this->themingDefaults = $themingDefaults;
	$this->urlGenerator = $urlGenerator;
	$this->l10nFactory = $l10nFactory;
	$this->htmlBody .= $this->head;
	$this->emailId = $emailId;
	$this->data = $data;
}
```

The support portal has a freely accessible [example app](https://portal.nextcloud.com/file.php?id=8) in which that `$emailId` is used to distinguish things:

```php
public function addBodyButtonGroup(
	string $textLeft, string $urlLeft,
	string $textRight, string $urlRight,
	string $plainTextLeft = '',
	string $plainTextRight = '') {

	// for the welcome email we omit the left button ("Install client") and only show the button that links to the instance
	if ($this->emailId === 'settings.Welcome') {
		parent::addBodyButton($textLeft, $urlLeft, $plainTextLeft);
		return;
	}
	parent::addBodyButtonGroup($textLeft, $urlLeft, $textRight, $urlRight, $plainTextLeft, $plainTextRight);
}
```

[email_template_example.zip](https://github.com/nextcloud/activity/files/6089433/email_template_example.zip)

So in the end, there seems to ALWAYS be ONE implementation of `IEMailTemplate` set per instance of Nextcloud only, because there's only one global config in `config.php` to do so. The attached example app seems to set that option automatically when enabling/disabling the app already using classes in `lib/Migration`.

    'mail_template_class' => '\OC\Mail\NameOfYourEmailTemplate'

Though being an instance wide implementation, that is able to distinguish differently requested mails for different purposes by the given `$emailId` and can dispatch to different additional implementations this way. Of course one needs to know which different purposes exist and stuff like that and I couldn't find any documentation for that yet. I guess the easiest way to find what one might be interest in is by searching the code base for `createEMailTemplate`.
