### ISSUE TITLE
Send notification on activity

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/activity#217]
Similar to the email sent out when activities happen, it would be nice to have a notification in Nextcloud being shown for activities. 

![bildschirmfoto vom 2017-11-08 18-15-36](https://user-images.githubusercontent.com/3404133/32563226-fa90e0b2-c4b0-11e7-99e2-4821a4eab543.png)

**Comment by juliushaertl** [comment]
@nickvergessen and @nextcloud/designers for the user experience

**Comment by skjnldsv** [comment]
Any kind of activity? I Can see some flood coing very fast :)

**Comment by nickvergessen** [comment]
Well the idea is that notifications require user interaction and activities are more like a "log".
Since we also have push notifications now on the mobile apps, we at least shouldn't do this by default.

**Comment by juliushaertl** [comment]
> Any kind of activity? I Can see some flood coing very fast :)

If it is implemented similar to the email notifications, users can simply check which actions they would like to be notified about.

Yes, we should make this optional. I get that activity is the log part, but I find it quite useful in team-working scenarios, if I get notified about changes immediately and can check what has been changed.

I also thought it might be more the responsibility of the apps to emit notifications for several events, but the activities settings give the user some control on what he would like to see.

**Comment by jancborchardt** [comment]
Not sure about this. We currently have a very limited amount of actions being put into notifications, like getting a federated share where you need to accept or reject. Or an incoming call.

Cluttering that with more regular stuff, even by choice, is not necessarily a thing we should do? :/ (And even if we add that column, most of them will be off by default.)

**Comment by nickvergessen** [comment]
@juliushaertl there is a huge difference: emails are grouped, notifications are not. I can see it on small instances (e.g. where you have only a hand full of file changes per week). however on company instances where multiple people work on the data 8hours a day it becomes very useless and even makes them all useless, since it makes it implossible to distinguish important from "noise".

I would recommend to do this manually in the app. E.g. the Talk/Spreed/Video calls app already does it manually and emits notifications and activity when you are invited to a room (when there happens a call in 13)

**Comment by juliushaertl** [comment]
@nickvergessen Ok, that makes sense. Lets close this. Thanks for clarifying.
