### ISSUE TITLE
Stream icons not visible in dark theme

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#335]
When you use the dark theme, the Activity stream looks like this (same in the file sidebar):
![dark theme activity stream](https://user-images.githubusercontent.com/925062/51314991-763ea180-1a51-11e9-82b9-b1dcc9e30126.png)    ![dark theme activity stream 2](https://user-images.githubusercontent.com/925062/51314989-75a60b00-1a51-11e9-8cbf-ae2c2692237a.png)

That’s because they are loaded in the `<img>` tag. Ideally it should be changed to use a class on the header like `icon-…` so it’s used as background-image and will automatically be adjusted to the theme color. Colored icons will stay like they are.

Documentation on that at: https://docs.nextcloud.com/server/latest/developer_manual/design/css.html#scss-icons-mixins

cc @nextcloud/designers

**Comment by nickvergessen** [comment]
The problem is a bit bigger, we send the images also to the desktop/mobile clients and they are part of the public API, while a CSS class is not part of the public API.

Also that would mean that ALL apps providing activities would need to load their CSS code on the files app and activity app.

Is the information "dark-theme" available via php code? then we can advice all the activity providers to read the property and send a white/black image accordingly.

**Comment by jancborchardt** [comment]
Oooh, good point. Then maybe easiest is to just add the activity stream icons to the dark theme css so they get inverted.

For that I would only need a class on each action block like "action-add" or "action-share" (or does thos exist already?) so that we can avoid inverting the colored icons like add and delete. :)

**Comment by nickvergessen** [comment]
Use the css filter `.activity-section .activity-icon > img.monochrome` or `.activity-section .activity-icon.monochrome img` to add `filter: invert(100%)` and I will make sure it's applied correctly.

**Comment by jancborchardt** [comment]
@nickvergessen cool, thanks! I’ll use `.activity-section .activity-icon.monochrome img`, fixed in https://github.com/nextcloud/server/pull/13648/commits/b8827ce64aa43c249f43f444c456f3e92f495861
