### ISSUE TITLE
Email notification time

### ISSUE THREAD

**Issue by sortengel** [nextcloud/activity#47]
### Feature request

In personal. Would it be possible to add an option to send the mail notification every 15 minutes also. Not just hourly, daily and weekly :)

**Comment by nickvergessen** [comment]
Yeah would be possible. However in the past the cron job was documented to run all 15 minutes. In which case the email could still be 29 minutes off in worst case. That's why the option was never added.
But yeah there is room for improvement here.

**Comment by HungryHowies** [comment]
I also was wondering  about Email Notification time. I tried to modify/fix this but unfortunately did not work as expected.
https://help.nextcloud.com/t/email-activity-notification/3543/3
This would be great if we had a choice within 15 minutes notification time.

**Comment by Sevey** [comment]
I personally would like to see it under 5 minutes.  Even better would be real-time.

**Comment by nickvergessen** [comment]
That is not what this feature was designed for. Also real time will slow down uploading and editing files, etc.

I will have a look at the cron and what we can do for the fastest option.

**Comment by Sevey** [comment]
Nick - Would you be able to elaborate on what it was designed for?  Perhaps we're simply not using it right or don't have the same thought process.

I'm using it to receive notifications of new folders that are shared with me primarily.  In today's age where Facebook, twitter and everything else is all delivered in real-time, I think it would be nice to see NextCloud doing the same.

Could you elaborate why a realtime email that says "User xya has shared abc with you" would slow down uploading files?  I think I'm only getting notifications of a file/folder being shared with me, not a file being uploaded or edited.  Those sound like they would be two very separate processes being interacted with so I'm confused as to why immediately sending a notification that a folder was shared (an access change) would slow down file uploads?  I admit I'm not a NextCloud expert but I'm looking to learn.

From our use case, I'll share a folder with someone, perhaps prior to a meeting.  20 minutes later when I talk to them I'll say "Hey did you have a chance to look at those files I sent over?", and they won't have known it was even shared with them yet.

**Comment by nickvergessen** [comment]
> Would you be able to elaborate on what it was designed for? Perhaps we're simply not using it right or don't have the same thought process.

Sure, that's why we are here, right?

> I'm using it to receive notifications of new folders that are shared with me primarily.

This was exactly my guess ;)
But I have good news for you in this case. Did you ever try a federated share? It creates a notification on our notification endpoint. This notification endpoint is already read by the desktop sync client and the mobile clients will follow in the near future.

For the "normal" (local) shares we are planning to do the same. (Can't find the issue right now, @rullzer ). But as soon as this is implemented, you phone/desktop will already notify you about the received share, so there is no more need to also send an email ;)

_As a side note:_
The share activity is not a huge slow down. However the activities which would be generated when you upload a file "User X has uploaded file Y" need to be generated for each user, with their paths, which required a lot of work and is very expensive under the hood.
