### ISSUE TITLE
Activity in extra database

### ISSUE THREAD

**Issue by PVince81** [nextcloud/activity#721]
Due to lots of writes (like #590) it might be useful for performance to move the activity table to a separate database.

- [ ] use separate DB connection / check if Doctrine can handle that
- [ ] config switches for configuring the second DB, off by default
- [ ] how to handle migrations ?

@nickvergessen

**Comment by nickvergessen** [comment]
- Server preparation on the connection factory to allow prefixing configs: https://github.com/nextcloud/server/pull/30973
- Activity app PR to make use of it: https://github.com/nextcloud/activity/pull/722

---

### HowTo

In config.php you can specify the new configs:
```
activity_dbuser (if undefined falls back to dbuser)
activity_dbpassword (if undefined falls back to dbpassword)
activity_dbname (if undefined falls back to dbname)
activity_dbhost (if undefined falls back to dbhost)
activity_dbdriveroptions (if undefined falls back to dbdriveroptions)
```

Remarks:
* Will fall back to normal behaviour but use a second connection atm
* It's not possible to use a different db type for activity than the rest
* There is no migration. In order to migrate one needs to:
    - Stop the webserver
    - Add config for second db connection
    - Copy the schema (optionally and data) to the new database
    - Restart the webserver
* On each schema change the sysadmins have to manually perform changes to the activity table

**Comment by PVince81** [comment]
oh, the backport bot is not happy here ? @nickvergessen can you have a look ?

the server PRs were merged already

**Comment by nickvergessen** [comment]
You try to backport a ticket, not a PR
